POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNpYW0iLCJpZCI6IjYxZTAzMGU2NTZkMGY2NmE4NGU3OTQzMiIsImlhdCI6MTY0MjMyNTIyNH0.OvQ7gNmzZbNHeWntc4_8gcFVFiKzObhnOnI3BwgMV5I

{
      "title": "New blog added by siam 4",
      "author": "Robert C. Martin",
      "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
      "likes": 2
}