POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYxZTAzMTA2NTZkMGY2NmE4NGU3OTQzNiIsImlhdCI6MTY0MjM1OTgyOH0.PzdfAE6yAjeaRPBWN_x4VQQ8_Z7KKrldwUb9lfal8no

{
      "title": "New blog added by root 4",
      "author": "Robert C. Martin",
      "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
      "likes": 2
}