DELETE http://localhost:3003/api/blogs/61e05aa2cf35b9f2b5ad2cce
Content-Type: application/application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjYxZTAzMTA2NTZkMGY2NmE4NGU3OTQzNiIsImlhdCI6MTY0MjMyODY4OH0.Az-5_-nz1JXh8wMwX-vk2V0RquhRee3JS8h_H_sYeU0